### ISSUE TITLE
object with belongsTo with an explicit foreign_key doesn't save

### ISSUE THREAD

**Issue by rodolforg** [taq/torm#12] opened 2016-01-06 04:13 UTC
When I use this code:
```
World::belongsTo('map1',array("class_name"=>"Map", 'foreign_key'=>'map1_id'));
World::belongsTo('map2',array("class_name"=>"Map", 'foreign_key'=>'map2_id'));

$rot->map1 = Map::where(['name' => maps[0]])->current();
$rot->map2 = Map::where(['name' => maps[1]])->current();
$rot->save();
```
I got these error messages:
> PHP Notice:  Undefined index: map1 in [...]/vendor/taq/torm/src/Persistence.php on line 164
> PHP Notice:  Undefined index: map2 in [...]/vendor/taq/torm/src/Persistence.php on line 164

I can bypass this error by coding though:
```
$rot->map1_id = Map::where(['name' => maps[0]])->current()->id;
$rot->map2_id = Map::where(['name' => maps[1]])->current()->id;
```

**Comment by taq** [comment] 2016-01-06 11:02
I just made a test called `testBelongsAttributionFromWhere()` where I try to replicate the conditions you show above, and it worked, without changing anything. Maybe there's something when you use more than one `belongsTo` association on the same object, but check the test, see if works, and if so, try to hack it to show the same situation above, and perhaps make a pull request. :-)

**Comment by rodolforg** [comment] 2016-01-06 15:03
You test runs just fine. So I changed your test file.
1) Added at its beginning :
```
class Tocket extends TORM\Model {
  public static function getNewPKValue() {
     return time()+rand();
  }
}
```
2) In the new `function testBelongsAttributionFromWhere()`, I changed `Ticket` class to `Tocket` (only two minor changes then):
```
        Tocket::belongsTo("person", ["class_name"  => "User", "foreign_key" => "user_id"]);

        $users               = [$user->code];
        $ticket              = new Tocket();
```
3) I created table "tockets" just like database table "tickets".
4) So I ran the tests and I got the same error.
> 1) ModelTest::testBelongsAttributionFromWhere
> Undefined index: person
> 
> [...]/vendor/taq/torm/src/Persistence.php:164
> [...]/vendor/taq/torm/src/Persistence.php:68
> [...]/vendor/taq/torm/test/modelTest.php:622

Warning: this lets databases/test.sqlite3 not as supposed to be.

**Comment by taq** [comment] 2016-01-06 15:52
Weird stuff. I was suspecting that two belongsTo could be the cause, but on your test is just one, right? Like the old Ticket association.

**Comment by rodolforg** [comment] 2016-01-06 17:30
Yes, only one belongTo; I described all the changes I made.

**Comment by taq** [comment] 2016-01-06 18:17
Please check the `issue12` branch to see if it works.

**Comment by rodolforg** [comment] 2016-01-07 10:42
It works, but I can see one problem: I cannot use _belongsTo_ twice with the same class.
I'd propose this change to BelongsTo.php:
```
    /**
     * Return the belongs foreign_key for a given attribute
     *
     * @param string $attr object attribute
     * 
     * @return string key found or null
     */
    private function _getBelongsKey($attr)
    {
        $cls = get_called_class();

        if (!array_key_exists($cls, self::$_belongs_to)
            || !array_key_exists($attr, self::$_belongs_to[$cls])
        ) {
        	return null;
    	}
	    $configs       = self::$_belongs_to[$cls][$attr];
	    $belongs_cls   = is_array($configs) && array_key_exists("class_name",  $configs) ? $configs["class_name"]  : ucfirst($attr);
	    $belongs_key   = is_array($configs) && array_key_exists("foreign_key", $configs) ? $configs["foreign_key"] : strtolower($belongs_cls)."_id";
	    return $belongs_key;
    }
```
And change Model.php to use $attr instead of $values in `__set()`.
```
    public function __set($attr, $value)
    {
        $ids = $this->_resolveIds($attr, $value);
        if ($ids) {
            return $ids;
        }

        $ids = $this->_resolveCollection($attr, $value);
        if ($ids) {
            return $ids;
        }

        // assigning an object, should be a belongs_to
        if (is_object($value)) {
            $bkey = $this->_getBelongsKey($attr); // This line changed
            if (!is_null($bkey)) {
                $ocls  = get_class($value);
                $okey  = $ocls::getPK();
                $attr  = $bkey;
                $value = $value->get($okey);
            }
        }
        $this->set($attr, $value);
    }
```

I didn't make a Pull Request, because I think it might have cache issues, when there is two consecutive (different) assignments to same attribute. (`BelongsTo::_belongs_cache`)

**Comment by taq** [comment] 2016-01-07 10:55
Your example of the `_getBelongsKey` have code different from the `issue12` branch, is the old code, did you checked how it works there?

**Comment by rodolforg** [comment] 2016-01-07 19:32
It looks like the same, but it is not.
I changed the function parameter (it was the value, now it is the attribute name).

**Comment by taq** [comment] 2016-01-07 19:45
The new code is this one here: https://github.com/taq/torm/blob/issue12/src/BelongsTo.php

```php
 private function _getBelongsKey($other)
    {
        $cls = get_called_class();
        if (!isset(self::$_belongs_to[$cls])) {
            return null;
        }
        $other   = strtolower(get_class($other));
        $idx     = $other;
        $foreign = strtolower($other)."_id";
        $found   = isset(self::$_belongs_to[$cls]) && isset(self::$_belongs_to[$cls][$other]) ? self::$_belongs_to[$cls][$other] : null;
        if (is_null($found)) {
            foreach (self::$_belongs_to[$cls] as $key => $val) {
                if (isset($val["class_name"]) && strtolower($other) == strtolower($val["class_name"])) {
                    $other = $val["class_name"];
                    $idx   = $key;
                }
                if (isset($val["foreign_key"]) && strtolower($other) == strtolower($val["class_name"])) {
                    $foreign = $val["foreign_key"];
                }
            }
        }
        if (!isset(self::$_belongs_to[$cls][$idx])) {
            return null;
        }
        return $foreign;
    }
```
It needs to dig on the belongsTo array to check if it finds the name of the association, and keep searching for the class name and foreign key.

**Comment by rodolforg** [comment] 2016-01-07 19:59
But why does it need to do that? It can be called by the attribute name, that is used as array key.
This code worked, but not if I have two belongsTo to same class, but through different attribute names (as my first example: map1 and map2).
If I do this as in first post:
```
$rot->map1 = Map::where(['name' => maps[0]])->current();
```
It would be `$rot->map2_id` that would change (the last attribute mapped in $_belongs_to[$cls] with class Map).
That is the reason I proposed the code in https://github.com/taq/torm/issues/12#issuecomment-169625950 (based on yours).

**Comment by taq** [comment] 2016-01-07 20:04
I'm making a test here with two belongsTo with *objects* (the main point of the changes), let see what is going on there.

**Comment by taq** [comment] 2016-01-07 20:12
Btw, you're right, the attribute approach is very simpler. :-) Wait a minute (or two).

**Comment by taq** [comment] 2016-01-07 20:19
Done, please check `issue12` branch again, *exactly* the way you suggested, and seems to work very fine. My main mistake was didn't make a test yesterday. Working with a test make all things less complex, and the way I tried to solve it was really unnecessary. :-p

**Comment by rodolforg** [comment] 2016-01-07 21:13
Yup. It is working fine.

**Comment by taq** [comment] 2016-01-07 22:03
If the value is null, we need to explicity set it to null, removing it's association, so, it make sense. 
Here we go again on `issue12` branch.

Btw, I'm working on other projects now (Rails projects) and don't have an project here where I use TORM (to be honest I'm using it just on one customer, that's the reason I made it on first place), so I don't have a database with a lot of results to test the `foreach` on issue#11. Can you test it for me?

**Comment by rodolforg** [comment] 2016-01-08 18:27
The branch `issue12` works fine for null assignment now.
But both cases (normal and null) have cache issues. The function `__set()` does not change the `_belongs_cache`.
So I was wondering if it would not be better to move the `set` code to `BelongsTo` class in order to update cache properly.

Another option is to rewrite `resolveBelongsTo()` like this for checking the id of cached object against current one:
```
    private function _resolveBelongsTo($attr, $values)
    {
        $cls = get_called_class();
        if (!array_key_exists($cls, self::$_belongs_to)
            || !array_key_exists($attr, self::$_belongs_to[$cls])
        ) {
            return null;
        }

        $configs       = self::$_belongs_to[$cls][$attr];
        $belongs_cls   = is_array($configs) && array_key_exists("class_name",  $configs) ? $configs["class_name"]  : ucfirst($attr);
        $belongs_key   = is_array($configs) && array_key_exists("foreign_key", $configs) ? $configs["foreign_key"] : strtolower($belongs_cls)."_id";
        $primary_key   = is_array($configs) && array_key_exists("primary_key", $configs) ? $configs["primary_key"] : "id";
        $value         = $values[$belongs_key];

// Here is the key change
        if (array_key_exists($attr, $this->_belongs_cache) && $this->_belongs_cache[$attr] && $this->_belongs_cache[$attr]->$primary_key == $value) {
            return $this->_belongs_cache[$attr];
        }

        $obj           = $belongs_cls::first(array($primary_key => $value));

        if ($obj) {
            $this->_belongs_cache[$attr] = $obj;
        }
        return $obj;
    }
```

**Comment by taq** [comment] 2016-01-08 20:05
No, the `set` method will stay on the `Model` class. Doesn't make sense to put it on `BelongsTo`, because simple assigment is done on the model, not just on associations. This issue is taking too long, I'll close it to release a new version and will check for cache issues later.

**Closed by taq** 2016-01-08 20:05 UTC

**Comment by rodolforg** [comment] 2016-01-08 20:26
Ok. But the cache issues exist since the first belongsTo assignment commit (https://github.com/taq/torm/commit/d6037a29a55d9ff4b2a3422c6c00ec53cf4cb00c). My pull-request https://github.com/taq/torm/pull/14 only uses `$ticket->user` attribute (not that custom `person`).

**Comment by taq** [comment] 2016-01-08 20:35
I saw it, taking a look there right now.
